import type { Metadata } from "next";
import { Geist, Geist_Mono } from "next/font/google";
import "./globals.css";
import { Web3Provider } from "@/utils/connexion/web3provider";
import { UserPoolsProvider } from "@/utils/hooks/LendingPoolFactory/useGetUserPools";
import { AllPoolsProvider } from "@/utils/hooks/LendingPoolFactory/useGetAllPools";

const geistSans = Geist({
  variable: "--font-geist-sans",
  subsets: ["latin"],
});

const geistMono = Geist_Mono({
  variable: "--font-geist-mono",
  subsets: ["latin"],
});

export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="en">
      <body
        className={`${geistSans.variable} ${geistMono.variable} antialiased`}
      >
        <Web3Provider>
          <UserPoolsProvider>
            <AllPoolsProvider>
              {children}
            </AllPoolsProvider>
          </UserPoolsProvider>
        </Web3Provider>
      </body>
    </html>
  );
}
